# Generated by Django 6.0.7 on 2026-07-23 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, help_text='Введите логин', max_length=35, null=True, verbose_name='Логин'),
        ),
    ]
