# Generated by Django 6.0.7 on 2026-07-23 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diarypost',
            options={'verbose_name': 'дневник', 'verbose_name_plural': 'дневники'},
        ),
    ]
