# Generated by Django 6.0.7 on 2026-07-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_alter_diarypost_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='diarypost',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
        ),
    ]
