# Generated by Django 6.0.7 on 2026-07-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_diarypost_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diarypost',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='previews/', verbose_name='Превью'),
        ),
    ]
